trainer:
  accelerator: auto
  default_root_dir: 'runs/noise/'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 3

data:
  class_path: data.LitDataModule
  init_args:
    inputs: ['output_ts_I', 'output_ts_Q']
    variables: ['energy_eV', 'pitch_angle_deg']
    observables: ['avg_axial_frequency_Hz', 'avg_carrier_frequency_Hz', 'radius_m']
    batch_size: 256
    num_workers: 1
    path: '/n/holystore01/LABS/iaifi_lab/Lab/creissel/neutrino_mass/combined_data_fullsim.hdf5'
    cutoff: 8192

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.75
    
model:
  class_path: model.LitS4Model
  init_args:
    d_input: &d_input 2
    d_output: &d_output 2
    encoder:
        class_path: models.networks.S4DModel
        init_args:
           d_input: *d_input
           d_output: *d_output
           d_model: 10
           n_layers: 6
           dropout: 0.0
           prenorm: False
           fc_hidden: [512, 256, 128]

