trainer:
  accelerator: auto
  default_root_dir: 'runs/input_I__output_energy_pitch__d_model_18_n_layers_6_gamma0.75_normX/'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  log_every_n_steps: 1
  max_epochs: 80

data:
  class_path: data.LitDataModule
  init_args:
    inputs: ['output_ts_I']
    variables: ['energy_eV', 'pitch_angle_deg']
    observables: ['avg_axial_frequency_Hz', 'avg_carrier_frequency_Hz', 'radius_m']
    noise_const: 0
    batch_size: 32
    num_workers: 1
    path: '/gpfs/gibbs/pi/heeger/hb637/ssm_files_pi_heeger/combined_data_fullsim.hdf5'

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-2

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.75

model:
  class_path: model.LitS4Model
  init_args:
    d_input: &d_input 1
    d_output: &d_output 2
    encoder:
        class_path: models.networks.S4DModel
        init_args:
           d_input: *d_input
           d_output: *d_output
           d_model: 18
           n_layers: 6
           dropout: 0.0
           prenorm: False
           fc_hidden: []
    loss: MSELoss
